In [ ]:
from google.colab import files

uploaded = files.upload()

Saving retail_sales_cleaned (1).csv to retail_sales_cleaned (1).csv

In [ ]:
import pandas as pd

df = pd.read_csv("retail_sales_cleaned (1).csv")

print(df.shape)
print(df.columns)
df.head()

(1500, 20)
Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Region', 'State', 'City',
       'Product_ID', 'Category', 'Sub_Category', 'Product_Name', 'Unit_Price',
       'Quantity', 'Discount', 'Sales', 'Profit'],
      dtype='object')

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,City,Product_ID,Category,Sub_Category,Product_Name,Unit_Price,Quantity,Discount,Sales,Profit
0,1,ORD-2023121,2023-01-02,2023-01-07,Standard Class,C-2029,Amelia Davis,Corporate,South,Georgia,Atlanta,P-1009,Technology,Laptops,Ultrabook,1073.17,1,0.40,643.90,-230.65
1,2,ORD-2023176,2023-01-02,2023-01-08,Standard Class,C-2208,Zoe Garcia,Consumer,East,Pennsylvania,Philadelphia,P-1021,Office Supplies,Binders,Heavy Duty Binder,9.25,3,0.00,27.75,13.64
2,3,ORD-2023479,2023-01-03,2023-01-03,Same Day,C-2158,Isabella Lopez,Consumer,East,Massachusetts,Boston,P-1010,Furniture,Chairs,Ergonomic Office Chair,222.50,4,0.05,845.50,211.82
3,4,ORD-2023175,2023-01-05,2023-01-11,Standard Class,C-2281,Sara Lewis,Consumer,West,California,San Francisco,P-1021,Office Supplies,Binders,Heavy Duty Binder,8.95,2,0.30,12.53,3.53
4,5,ORD-2023287,2023-01-08,2023-01-13,Standard Class,C-2134,Henry Lopez,Consumer,West,California,Los Angeles,P-1012,Furniture,Chairs,Visitor Chair,101.96,2,0.00,203.92,56.42

In [ ]:
df.head()
df.tail()
df.shape
df.columns
df.info()
df.dtypes
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         1500 non-null   int64
 1   Order_ID       1500 non-null   object
 2   Order_Date     1500 non-null   object
 3   Ship_Date      1500 non-null   object
 4   Ship_Mode      1500 non-null   object
 5   Customer_ID    1500 non-null   object
 6   Customer_Name  1500 non-null   object
 7   Segment        1500 non-null   object
 8   Region         1500 non-null   object
 9   State          1500 non-null   object
 10  City           1500 non-null   object
 11  Product_ID     1500 non-null   object
 12  Category       1500 non-null   object
 13  Sub_Category   1500 non-null   object
 14  Product_Name   1500 non-null   object
 15  Unit_Price     1500 non-null   float64
 16  Quantity       1500 non-null   int64
 17  Discount       1500 non-null   float64
 18  Sales          1500 non-null   float64
 19  Profit         1500 non-null   float64
dtypes: float64(4), int64(2), object(14)
memory usage: 234.5+ KB

,Row_ID,Unit_Price,Quantity,Discount,Sales,Profit
count,1500.000000,1500.000000,1500.00000,1500.000000,1500.00000,1500.000000
mean,750.500000,108.523387,2.50000,0.135100,157.24256,18.636073
std,433.157015,223.596723,1.85696,0.130784,353.04940,59.390410
min,1.000000,5.820000,1.00000,0.000000,3.52000,-588.800000
25%,375.750000,8.810000,1.00000,0.000000,16.68750,3.995000
50%,750.500000,15.110000,2.00000,0.100000,41.21500,10.755000
75%,1125.250000,99.370000,3.00000,0.200000,141.76250,27.547500
max,1500.000000,1428.520000,10.00000,0.400000,4516.24000,628.810000

In [ ]:
df.nunique()

Row_ID           1500
Order_ID         1239
Order_Date        727
Ship_Date         718
Ship_Mode           4
Customer_ID       257
Customer_Name     257
Segment             3
Region              4
State              14
City               16
Product_ID         24
Category            3
Sub_Category        9
Product_Name       24
Unit_Price        910
Quantity            8
Discount            7
Sales            1384
Profit           1265
dtype: int64

In [ ]:
df["Category"].unique()
df["Region"].unique()
df["Segment"].unique()
df["Ship_Mode"].unique()

array(['Standard Class', 'Same Day', 'Second Class', 'First Class'],
      dtype=object)

In [ ]:
df.isnull().sum()

Row_ID           0
Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Region           0
State            0
City             0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Unit_Price       0
Quantity         0
Discount         0
Sales            0
Profit           0
dtype: int64

In [ ]:
(df.isnull().sum() / len(df)) * 100

Row_ID           0.0
Order_ID         0.0
Order_Date       0.0
Ship_Date        0.0
Ship_Mode        0.0
Customer_ID      0.0
Customer_Name    0.0
Segment          0.0
Region           0.0
State            0.0
City             0.0
Product_ID       0.0
Category         0.0
Sub_Category     0.0
Product_Name     0.0
Unit_Price       0.0
Quantity         0.0
Discount         0.0
Sales            0.0
Profit           0.0
dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"])

df.dtypes

Row_ID                    int64
Order_ID                 object
Order_Date       datetime64[ns]
Ship_Date        datetime64[ns]
Ship_Mode                object
Customer_ID              object
Customer_Name            object
Segment                  object
Region                   object
State                    object
City                     object
Product_ID               object
Category                 object
Sub_Category             object
Product_Name             object
Unit_Price              float64
Quantity                  int64
Discount                float64
Sales                   float64
Profit                  float64
dtype: object

In [ ]:
df["Shipping_Days"] = (
    df["Ship_Date"] - df["Order_Date"]
).dt.days

df["Revenue_per_Unit"] = df["Sales"] / df["Quantity"]

df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,...,Category,Sub_Category,Product_Name,Unit_Price,Quantity,Discount,Sales,Profit,Shipping_Days,Revenue_per_Unit
0,1,ORD-2023121,2023-01-02,2023-01-07,Standard Class,C-2029,Amelia Davis,Corporate,South,Georgia,...,Technology,Laptops,Ultrabook,1073.17,1,0.40,643.90,-230.65,5,643.900
1,2,ORD-2023176,2023-01-02,2023-01-08,Standard Class,C-2208,Zoe Garcia,Consumer,East,Pennsylvania,...,Office Supplies,Binders,Heavy Duty Binder,9.25,3,0.00,27.75,13.64,6,9.250
2,3,ORD-2023479,2023-01-03,2023-01-03,Same Day,C-2158,Isabella Lopez,Consumer,East,Massachusetts,...,Furniture,Chairs,Ergonomic Office Chair,222.50,4,0.05,845.50,211.82,0,211.375
3,4,ORD-2023175,2023-01-05,2023-01-11,Standard Class,C-2281,Sara Lewis,Consumer,West,California,...,Office Supplies,Binders,Heavy Duty Binder,8.95,2,0.30,12.53,3.53,6,6.265
4,5,ORD-2023287,2023-01-08,2023-01-13,Standard Class,C-2134,Henry Lopez,Consumer,West,California,...,Furniture,Chairs,Visitor Chair,101.96,2,0.00,203.92,56.42,5,101.960

In [ ]:
df["Shipping_Days"] = (
    df["Ship_Date"] - df["Order_Date"]
).dt.days

df["Revenue_per_Unit"] = df["Sales"] / df["Quantity"]

df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,...,Category,Sub_Category,Product_Name,Unit_Price,Quantity,Discount,Sales,Profit,Shipping_Days,Revenue_per_Unit
0,1,ORD-2023121,2023-01-02,2023-01-07,Standard Class,C-2029,Amelia Davis,Corporate,South,Georgia,...,Technology,Laptops,Ultrabook,1073.17,1,0.40,643.90,-230.65,5,643.900
1,2,ORD-2023176,2023-01-02,2023-01-08,Standard Class,C-2208,Zoe Garcia,Consumer,East,Pennsylvania,...,Office Supplies,Binders,Heavy Duty Binder,9.25,3,0.00,27.75,13.64,6,9.250
2,3,ORD-2023479,2023-01-03,2023-01-03,Same Day,C-2158,Isabella Lopez,Consumer,East,Massachusetts,...,Furniture,Chairs,Ergonomic Office Chair,222.50,4,0.05,845.50,211.82,0,211.375
3,4,ORD-2023175,2023-01-05,2023-01-11,Standard Class,C-2281,Sara Lewis,Consumer,West,California,...,Office Supplies,Binders,Heavy Duty Binder,8.95,2,0.30,12.53,3.53,6,6.265
4,5,ORD-2023287,2023-01-08,2023-01-13,Standard Class,C-2134,Henry Lopez,Consumer,West,California,...,Furniture,Chairs,Visitor Chair,101.96,2,0.00,203.92,56.42,5,101.960

In [ ]:
  df["Sales"].sum()

np.float64(235863.84000000003)

In [ ]:
df["Profit"].sum()

np.float64(27954.11)

In [ ]:
df["Quantity"].sum()

np.int64(3750)

In [ ]:
df["Sales"].mean()

np.float64(157.24256000000003)

In [ ]:
df["Profit"].mean()

np.float64(18.636073333333332)

In [ ]:
df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Technology         119627.44
Furniture           83458.25
Office Supplies     32778.15
Name: Sales, dtype: float64

In [ ]:
df.groupby("Region")[["Sales", "Profit"]].sum()

            Sales    Profit
Region
Central  26867.55   2287.20
East     70299.69   8397.74
South    63866.25   7033.97
West     74830.35  10235.20

In [ ]:
df.groupby("Product_Name")["Sales"].sum().sort_values(
    ascending=False
).head(10)

Product_Name
Ultrabook                  36008.41
Gaming Laptop              23875.31
Ergonomic Office Chair     15920.47
Executive Chair            14838.48
Business Laptop            12705.95
Conference Table           12470.25
iPhone-class Smartphone    12104.93
Android Smartphone         10874.82
Coffee Table                9485.62
Standing Desk               8465.38
Name: Sales, dtype: float64

In [ ]:
profile = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Unique Values": df.nunique(),
    "Missing Values": df.isnull().sum(),
    "Missing %": (df.isnull().sum() / len(df) * 100).round(2)
})

,Column,Data Type,Unique Values,Missing Values,Missing %
Row_ID,Row_ID,int64,1500,0,0.0
Order_ID,Order_ID,object,1239,0,0.0
Order_Date,Order_Date,datetime64[ns],727,0,0.0
Ship_Date,Ship_Date,datetime64[ns],718,0,0.0
Ship_Mode,Ship_Mode,object,4,0,0.0
Customer_ID,Customer_ID,object,257,0,0.0
Customer_Name,Customer_Name,object,257,0,0.0
Segment,Segment,object,3,0,0.0
Region,Region,object,4,0,0.0
State,State,object,14,0,0.0
City,City,object,16,0,0.0
Product_ID,Product_ID,object,24,0,0.0
Category,Category,object,3,0,0.0
Sub_Category,Sub_Category,object,9,0,0.0
Product_Name,Product_Name,object,24,0,0.0
Unit_Price,Unit_Price,float64,910,0,0.0
Quantity,Quantity,int64,8,0,0.0
Discount,Discount,float64,7,0,0.0
Sales,Sales,float64,1384,0,0.0
Profit,Profit,float64,1265,0,0.0
Shipping_Days,Shipping_Days,int64,8,0,0.0
Revenue_per_Unit,Revenue_per_Unit,float64,1348,0,0.0